#!/sbin/busybox sh

FILEVAR=logger

if [ $2 -eq "module" ];then
	if [ -z $3 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			lsmod | grep logger
			ON=`echo $?`
			if [ $ON -eq 1 ]; then
				VAL="off"
			else
				VAL="on"
			fi

			eval $FILEVAR=$VAL
			echo $FILEVAR=$VAL >> $DEFAULT_PROFILE
		fi
	else
		if [ "$CONTROLSWITCH_LOGGER" == "on" -o "$CONFIG_BOOTED" == "true" ]; then
			case "$3" in
				off)	rmmod /lib/modules/logger.ko	;;
				on)	insmod /lib/modules/logger.ko	;;
			esac
		fi
		eval $FILEVAR=$3
	fi

	eval echo \$$FILEVAR

elif [ $2 -eq "switch" ];then
	if [ -z $3 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			ON=`cat /sys/kernel/logger_mode/logger_mode`
			if [ $ON -eq 0 ]; then
				VAL="off"
			else
				VAL="on"
			fi

			eval $FILEVAR=$VAL
			echo $FILEVAR=$VAL >> $DEFAULT_PROFILE
		fi
	else
		if [ "$CONTROLSWITCH_LOGGER" == "on" -o "$CONFIG_BOOTED" == "true" ]; then
			case "$3" in
				off)	echo 0 > /sys/kernel/logger_mode/logger_mode	;;
				on)	echo 1 > /sys/kernel/logger_mode/logger_mode	;;
			esac
		fi
		eval $FILEVAR=$3
	fi

	eval echo \$$FILEVAR
fi
