#!/sbin/busybox sh

if [ -f /lib/modules/logger.ko ]; then
    lsmod | grep logger
    ON=`echo $?`
    if [ $ON -eq 1 ]; then
        if [ "$2" == "switch" ]; then
	    insmod /lib/modules/logger.ko
            echo "Android Logger: Enabled"
        else
            echo "Android Logger: Disabled"
        fi
    else
        if [ "$2" == "switch" ]; then
            rmmod logger
            echo "Android Logger: Disabled"
        else
            echo "Android Logger: Enabled"
        fi
    fi
elif [ -f /sys/kernel/logger_mode/logger_mode ]; then
    ON=`cat /sys/kernel/logger_mode/logger_mode`
    if [ $ON -eq 0 ]; then
        if [ "$2" == "switch" ]; then
            echo 1 > /sys/kernel/logger_mode/logger_mode
            echo "Android Logger: Enabled"
        else
            echo "Android Logger: Disabled"
        fi
    else
        if [ "$2" == "switch" ]; then
            echo 0 > /sys/kernel/logger_mode/logger_mode
            echo "Android Logger: Disabled"
        else
            echo "Android Logger: Enabled"
        fi
    fi
fi
