#!/sbin/busybox sh

STEP=GPU_VOLT_`echo $2`

if [ -z $3 ]; then
	evalcmd='eval echo \$$STEP'
	if [ "a`eval $evalcmd`" == "a" ]; then
		while read FREQ UVOLT; do
			eval "GPU_VOLT_$FREQ=$UVOLT"
			echo "GPU_VOLT_$FREQ=$UVOLT" >> $DEFAULT_PROFILE
		done < /sys/devices/platform/pvrsrvkm.0/sgx_dvfs_volt_table
	fi
else
	eval $STEP=$3

	if [ "$CONTROLSWITCH_GPU" == "on" -o "$CONFIG_BOOTED" == true ]; then
		VOLTAGES=""
		while read FREQ UVOLT; do
			evalcmd='eval echo \$GPU_VOLT_$FREQ'
			VOLTAGES="$VOLTAGES `eval $evalcmd`"
		done < /sys/devices/platform/pvrsrvkm.0/sgx_dvfs_volt_table

		echo $VOLTAGES > /sys/devices/platform/pvrsrvkm.0/sgx_dvfs_volt_table
	fi
fi

eval echo \$$STEP
