#!/sbin/busybox sh

if [ -f '/lib/modules/logger.ko' ]; then
    lsmod | grep logger
    ON=`echo $?`
    if [ $ON -eq 1 ]; then
        insmod /lib/modules/logger.ko
        echo "Enabled Android Logger"
    else
        rmmod logger
        echo "Disabled Android Logger"
    fi
elif [ -f '/sys/kernel/logger_mode/logger_mode' ]; then
    ON=`cat /sys/kernel/logger_mode/logger_mode`
    if [ $ON -eq 0 ]; then
        echo 1 > /sys/kernel/logger_mode/logger_mode
        echo "Enabled Android Logger"
    else
        echo 0 > /sys/kernel/logger_mode/logger_mode
        echo "Disabled Android Logger"
    fi
else
        echo "Android Logger Missing"
fi
